import React from 'react';
import { createRoot } from 'react-dom/client';
import { AreaChart, Area, ResponsiveContainer, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts';
import { Activity, ArrowDownRight, ArrowUpRight, LockKeyhole, Radio, Shield, Zap } from 'lucide-react';
import './style.css';

type Tick={symbol:string;timestamp:string;bid:string;ask:string;bid_size:string;ask_size:string;last_price:string|null;last_trade_size:string|null;received_ms:number;source:string};
type Position={quantity:string;average:string;realized:string;unrealized:string;exposure:string};
type Fill={order_id:string;symbol:string;side:string;quantity:string;signal_price:string;execution_price:string;fee:string;slippage:string;timestamp:string;strategy_reason:string;realized_pnl:string};
type Snapshot={mode:'live'|'demo';session:string;connected:boolean;trading:boolean;stale:Record<string,boolean>;market:Record<string,Tick>;portfolio:{cash:string;equity:string;pnl:string;return_pct:string;drawdown:string;fees:string;trades:number;win_rate:string;daily_pnl:string;positions:Record<string,Position>};benchmark:{equity:string;return_pct:string}|null;risk:{killed:boolean;daily_halt:boolean;max_daily_loss:string;max_positions:Record<string,string>;rejections:{symbol:string;action:string;reason:string;timestamp:string}[]};fills:Fill[];signals:{symbol:string;action:string;reason:string;timestamp:string}[];curve:{timestamp:string;equity:string;benchmark:string|null}[];updated_at:string};
const money=(v:string|number|undefined, digits=2)=>v===undefined?'—':Number(v).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:digits,minimumFractionDigits:digits});
const num=(v:string|number|undefined,digits=4)=>v===undefined?'—':Number(v).toLocaleString('en-US',{maximumFractionDigits:digits});
const time=(v:string|undefined)=>v?new Date(v).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';
function App(){
 const [state,setState]=React.useState<Snapshot|null>(null);const [connected,setConnected]=React.useState(false);const [error,setError]=React.useState('');const [token,setToken]=React.useState(sessionStorage.getItem('paper_control_token')||'');const [draft,setDraft]=React.useState('');
 React.useEffect(()=>{let socket:WebSocket|null=null;let timer:number;let active=true;let delay=1000;
 const connect=()=>{if(!active)return;socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);socket.onopen=()=>{setConnected(true);delay=1000;setError('')};socket.onmessage=e=>{try{setState(JSON.parse(e.data) as Snapshot)}catch{setError('Bad state from server')}};socket.onclose=()=>{setConnected(false);if(active){timer=window.setTimeout(connect,delay);delay=Math.min(delay*2,15000)}};socket.onerror=()=>setError('Dashboard connection interrupted')};connect();return()=>{active=false;clearTimeout(timer);socket?.close()};
 },[]);
 async function control(path:string,body?:object){try{const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Control-Token':token},body:JSON.stringify(body??{})});if(!response.ok){setError(`Control rejected (${response.status}): ${await response.text()}`);return}setError('')}catch{setError('Control request failed')}}
 const portfolio=state?.portfolio;const rows=state?.curve.map(v=>({time:time(v.timestamp),equity:Number(v.equity),benchmark:v.benchmark?Number(v.benchmark):null}))||[];
 return <div className="shell"><div className="mast"><div className="logo"><div className="logoMark"><Activity size={20}/></div><span>ATLAS<span className="slash"> / </span>MARKET SYSTEMS</span></div><span className="mastRight">A SYSTEMS ENGINEERING DEMONSTRATION <span className="mastDot">●</span> PAPER ONLY</span></div>
 <main><header className="header"><div><div className="eyebrow"><span className="pulse"/> {state?.mode==='live'?'LIVE PUBLIC MARKET DATA':state?.mode==='demo'?'SYNTHETIC DEMO MODE':'WAITING FOR DATA'} <span className="sep">/</span> BTC & ETH SPOT</div><h1>Paper trading<span className="accent">.</span></h1><p className="sub">A risk-controlled execution simulator on public market data. No real orders. No real capital.</p></div><div className="headerStatus"><div className="statusTag"><Radio size={15}/>{connected && state?.connected?'FEED CONNECTED':'FEED DISCONNECTED'}</div><div className="statusTag"><Shield size={15}/>{state?.risk.killed?'KILL SWITCH ON':state?.risk.daily_halt?'LOSS HALT':state?.trading?'SIMULATOR ACTIVE':'SIMULATOR PAUSED'}</div><span className="asof">Last update {time(state?.updated_at)}</span></div></header>
 {error&&<div className="alert">{error}</div>}{!state&&<div className="empty">Connecting to the paper engine… No results are shown until data arrives.</div>}
 {state&&<><section className="metrics"><Metric title="PORTFOLIO EQUITY" value={money(portfolio?.equity)} note={`Start ${money(Number(portfolio?.equity)-Number(portfolio?.pnl))}`} icon={<Activity size={17}/>} /><Metric title="NET PAPER P&L" value={money(portfolio?.pnl)} note={`${num(portfolio?.return_pct,2)}% total return · fees included`} icon={Number(portfolio?.pnl)>=0?<ArrowUpRight size={17}/>:<ArrowDownRight size={17}/>} tone={Number(portfolio?.pnl)>=0?'positive':'negative'}/><Metric title="BUY & HOLD" value={state.benchmark?money(state.benchmark.equity):'Waiting for both pairs'} note={state.benchmark?`${num(state.benchmark.return_pct,2)}% equal-weight BTC/ETH`:'Needs both first quotes'} icon={<Zap size={17}/>} /><Metric title="MAX DRAWDOWN" value={money(portfolio?.drawdown)} note={`${portfolio?.trades??0} paper fills · ${money(portfolio?.fees)} fees`} icon={<ArrowDownRight size={17}/>} /></section>
 <div className="grid"><section className="panel chart"><div className="panelHead"><div><span className="overline">PERFORMANCE</span><h2>Equity over time</h2></div><div className="legend"><i className="strategy"/> Strategy <i className="benchmark"/> Buy & hold</div></div><div className="plot">{rows.length>1?<ResponsiveContainer width="100%" height="100%"><AreaChart data={rows}><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#79dfbb" stopOpacity=".19"/><stop offset="100%" stopColor="#79dfbb" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#28333e" vertical={false} strokeDasharray="2 5"/><XAxis dataKey="time" tick={{fill:'#8b9aa9',fontSize:11}} tickLine={false} axisLine={false} minTickGap={35}/><YAxis tick={{fill:'#8b9aa9',fontSize:11}} tickLine={false} axisLine={false} domain={['auto','auto']} tickFormatter={v=>`$${(v/1000).toFixed(1)}k`} width={62}/><Tooltip contentStyle={{background:'#18222d',border:'1px solid #31414e',borderRadius:8,color:'#e6f2f0'}} formatter={v=>money(Number(v))}/><Area dataKey="equity" type="monotone" stroke="#79dfbb" strokeWidth={2.5} fill="url(#area)" dot={false} name="Strategy"/><Area dataKey="benchmark" type="monotone" stroke="#8aa5d8" strokeWidth={1.7} fill="none" dot={false} name="Benchmark"/></AreaChart></ResponsiveContainer>:<div className="empty">The equity curve will appear as paper ticks arrive.</div>}</div><div className="panelFoot">Observed session only · No claim of profitability · Maximum drawdown is the peak-to-trough of observed snapshots</div></section>
 <section className="panel markets"><div className="panelHead"><div><span className="overline">01 / MARKET DATA</span><h2>Live quotes</h2></div><Radio size={17} className="mutedIcon"/></div>{['BTCUSDT','ETHUSDT'].map(symbol=>{const t=state.market[symbol],pos=portfolio?.positions[symbol];return <div className="market" key={symbol}><div className="marketName"><strong>{symbol.slice(0,3)}<span>/USDT</span></strong><span className={state.stale[symbol]?'chip bad':'chip good'}>{state.stale[symbol]?'STALE':'CURRENT'}</span></div><div className="quote"><span>BEST BID <b>{money(t?.bid)}</b></span><span>BEST ASK <b>{money(t?.ask)}</b></span></div><div className="marketMeta"><span>Spread <b>{t?money(Number(t.ask)-Number(t.bid)):'—'}</b></span><span>Mid <b>{t?money((Number(t.ask)+Number(t.bid))/2):'—'}</b></span><span>Last trade <b>{money(t?.last_price??undefined)}</b></span><span>Position <b>{num(pos?.quantity,6)}</b></span></div><small>{t?`${t.source} · ${time(t.timestamp)} · last trade qty ${num(t.last_trade_size??undefined,5)}`:'Awaiting first valid quote'}</small></div>})}</section>
 <section className="panel risk"><div className="panelHead"><div><span className="overline">02 / GUARDRAILS</span><h2>Risk & controls</h2></div><Shield size={17} className="mutedIcon"/></div><div className="riskRows"><Row title="New paper orders" value={state.trading?'ENABLED':'HALTED'} danger={!state.trading}/><Row title="Daily P&L" value={money(portfolio?.daily_pnl)} danger={Number(portfolio?.daily_pnl)<0}/><Row title="Daily loss limit" value={money(state.risk.max_daily_loss)}/><Row title="BTC position cap" value={`${num(state.risk.max_positions.BTCUSDT)} BTC`}/><Row title="ETH position cap" value={`${num(state.risk.max_positions.ETHUSDT)} ETH`}/><Row title="Cash" value={money(portfolio?.cash)}/></div><div className="control"><div className="controlHeading"><LockKeyhole size={14}/> Control token required</div><div className="controlForm"><input type="password" autoComplete="off" aria-label="Control token" placeholder="Enter local control token" value={draft} onChange={e=>setDraft(e.target.value)}/><button onClick={()=>{sessionStorage.setItem('paper_control_token',draft);setToken(draft);setDraft('')}}>Unlock</button></div><div className="controlActions"><button className="dangerButton" disabled={!token||state.risk.killed} onClick={()=>control('/api/kill-switch',{enabled:true})}>ACTIVATE KILL SWITCH</button><button disabled={!token||!state.risk.killed} onClick={()=>control('/api/kill-switch',{enabled:false})}>Resume</button><button disabled={!token} onClick={()=>{if(window.confirm('Start a fresh paper session? Current session remains in the database.'))control('/api/reset-session')}}>Reset session</button></div><small>Control token stays in this browser tab's session storage, not the URL.</small></div>{state.risk.rejections.length>0&&<div className="rejections"><span className="overline">LATEST REJECTION</span><p>{state.risk.rejections.at(-1)?.reason}</p><small>{state.risk.rejections.at(-1)?.symbol} · {time(state.risk.rejections.at(-1)?.timestamp)}</small></div>}</section>
 <section className="panel positions"><div className="panelHead"><div><span className="overline">03 / INVENTORY</span><h2>Paper positions</h2></div><span className="tiny">CASH-ONLY · LONG / FLAT</span></div><div className="tableWrap"><table><thead><tr><th>MARKET</th><th>QTY</th><th>AVG ENTRY</th><th>MARK</th><th>UNREALIZED</th><th>EXPOSURE</th></tr></thead><tbody>{Object.entries(portfolio?.positions||{}).map(([symbol,pos])=><tr key={symbol}><td className="bright">{symbol}</td><td>{num(pos.quantity,6)}</td><td>{money(pos.average)}</td><td>{state.market[symbol]?money((Number(state.market[symbol].bid)+Number(state.market[symbol].ask))/2):'—'}</td><td className={Number(pos.unrealized)>=0?'up':'down'}>{money(pos.unrealized)}</td><td>{money(pos.exposure)}</td></tr>)}</tbody></table></div></section>
 <section className="panel activity"><div className="panelHead"><div><span className="overline">04 / AUDIT TRAIL</span><h2>Paper fills & decisions</h2></div><span className="tiny">SIMULATED · NEVER EXCHANGE ORDERS</span></div>{state.fills.length===0?<div className="empty">No paper fills in this session. Signals and risk rejections appear below as they happen.</div>:<div className="tableWrap"><table><thead><tr><th>TIME</th><th>PAIR / SIDE</th><th>QTY</th><th>SIGNAL MID</th><th>FILL</th><th>FEE</th><th>SLIPPAGE</th><th>WHY</th></tr></thead><tbody>{[...state.fills].reverse().slice(0,12).map(f=><tr key={f.order_id}><td>{time(f.timestamp)}</td><td className="bright">{f.symbol} <span className={f.side==='BUY'?'up':'down'}>{f.side}</span></td><td>{num(f.quantity,6)}</td><td>{money(f.signal_price)}</td><td>{money(f.execution_price)}</td><td>{money(f.fee)}</td><td>{money(f.slippage,4)}</td><td className="why">{f.strategy_reason}</td></tr>)}</tbody></table></div>}<div className="latestSignal">Latest signal: {state.signals.length?state.signals.at(-1)?.reason:'Waiting for rolling-window data'} · Short signals in this cash-only model are rejected rather than faked as fills.</div></section></div>
 <footer>ATLAS / PAPER ENGINE <span>Market data: {state.mode==='live'?'Binance public streams':'synthetic and deterministic'} · Simulated execution only · Not financial advice</span></footer></>}
 </main></div>}
function Metric({title,value,note,icon,tone}:{title:string,value:string,note:string,icon:React.ReactNode,tone?:string}){return <div className="metric"><div className="metricTop"><span>{title}</span>{icon}</div><strong className={tone||''}>{value}</strong><small>{note}</small></div>}
function Row({title,value,danger}:{title:string,value:string,danger?:boolean}){return <div className="row"><span>{title}</span><strong className={danger?'down':''}>{value}</strong></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
